In [6]:
import requests
from bs4 import BeautifulSoup
import pandas as pd

# URL da página
url = "https://fbref.com/pt/comps/24/cronograma/Serie-A-Resultados-e-Calendarios"
# Faz a requisição para a página
response = requests.get(url)
soup = BeautifulSoup(response.content, "html.parser")

# Função para extrair a tabela da página
def extrair_tabela(rows):
    headers = []
    data = []
    
    for row in rows:
        cols = row.find_all(['th', 'td'])
        if len(headers) == 0:  # A primeira linha será o cabeçalho
            headers = [col.get_text
                       (strip=True) for col in cols]
        else:  # Demais linhas são dados
            data.append([col.get_text(strip=True) for col in cols])
    
    # Cria o DataFrame
    return pd.DataFrame(data, columns=headers)

# Encontra o container da tabela
table_container = soup.find('div', {'class': 'table_container'})
rows = table_container.find_all('tr')

# Extrai a tabela
tabela = extrair_tabela(rows)

# Encontra a coluna "Relatório da Partida"
links_relatorios = []
for row in rows:
    a_tag = row.find('a', text='Relatório da Partida')
    if a_tag:
        href = a_tag.get('href')
        if href and href != "#":  # Ignora links vazios ou "#" como marcador
            links_relatorios.append(href)
        else:
            links_relatorios.append(None)
    else:
        links_relatorios.append(None)

# Remove linhas onde a coluna "Relatório da Partida" é "Confronto"
tabela = tabela[~tabela['Relatório da Partida'].str.contains("Confronto", na=False)]

# Adiciona a coluna de links na tabela
tabela['Link Relatório'] = links_relatorios[:len(tabela)]  # Ajusta o tamanho da lista para o tamanho da tabela

C:\Users\eduar\AppData\Local\Temp\ipykernel_7244\3731441437.py:37: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  a_tag = row.find('a', text='Relatório da Partida')

In [7]:
# Desloca a coluna "Link Relatório" uma linha para cima
tabela['Link Relatório'] = tabela['Link Relatório'].shift(-1)

# Preenche a última linha da coluna "Link Relatório" com NaN (caso não esteja automaticamente)
tabela.loc[tabela.index[-1], 'Link Relatório'] = None

In [8]:
# Remove linhas onde "Link Relatório" é None
tabela = tabela[tabela['Link Relatório'].notna()]

In [9]:
tabela

,Sem,Dia,Data,Horário,Em casa,xG,Resultado,xG,Visitante,Público,Local,Árbitro,Relatório da Partida,Notas,Link Relatório
0,1,sáb,2024-04-13,18:30,Criciúma,0.7,1–1,0.6,Juventude,12.804,Estádio Heriberto Hülse,,Relatório da Partida,,/pt/partidas/60ef737d/Criciuma-Juventude-2024A...
1,1,sáb,2024-04-13,18:30,Internacional,1.9,2–1,0.7,Bahia,19.103,Estádio José Pinheiro Borba,,Relatório da Partida,,/pt/partidas/620b512a/Internacional-Bahia-2024...
2,1,dom,2024-04-14,16:00,Ath Paranaense,2.0,4–0,0.3,Cuiabá,21.388,Ligga Arena,,Relatório da Partida,,/pt/partidas/086cf01e/Athletico-Paranaense-Cui...
3,1,dom,2024-04-14,16:00,Vasco da Gama,0.9,2–1,1.2,Grêmio,17.722,Estádio Club de Regatas Vasco da Gama,,Relatório da Partida,,/pt/partidas/865e8350/Vasco-da-Gama-Gremio-202...
4,1,dom,2024-04-14,16:00,Corinthians,0.5,0–0,0.3,Atlético Mineiro,44.285,Neo Química Arena,,Relatório da Partida,,/pt/partidas/d3926429/Corinthians-Atletico-Min...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
393,34,sex,2024-11-22,21:30,Fluminense,0.8,2–2,1.3,Fortaleza,,Estadio Jornalista Mário Filho,Raphael Claus,Relatório da Partida,,/pt/partidas/d8463264/Fluminense-Fortaleza-202...
395,35,dom,2024-11-24,16:00,Bahia,2.2,1–1,0.8,Ath Paranaense,,Itaipava Arena Fonte Nova,Rodrigo José Pereira de Lima,Relatório da Partida,,/pt/partidas/571b8b37/Bahia-Athletico-Paranaen...
396,35,dom,2024-11-24,16:00,Internacional,2.8,4–1,0.3,Red Bull Bragantino,,Estádio José Pinheiro Borba,Marcelo de Lima Henrique,Relatório da Partida,,/pt/partidas/bd40427d/Internacional-Red-Bull-B...
397,35,dom,2024-11-24,16:00,Corinthians,1.2,3–1,0.3,Vasco da Gama,,Neo Química Arena,Davi de Oliveira Lacerda,Relatório da Partida,,/pt/partidas/cc1dd787/Corinthians-Vasco-da-Gam...
398,35,sáb,2024-11-23,21:30,São Paulo,1.0,2–2,1.0,Atlético Mineiro,,Estádio do Morumbi,Alex Gomes Stefano,Relatório da Partida,,/pt/partidas/45170f90/Sao-Paulo-Atletico-Minei...

In [10]:
tabela['Link Relatório'].tolist()

['/pt/partidas/60ef737d/Criciuma-Juventude-2024Abril13-Serie-A',
 '/pt/partidas/620b512a/Internacional-Bahia-2024Abril13-Serie-A',
 '/pt/partidas/086cf01e/Athletico-Paranaense-Cuiaba-2024Abril14-Serie-A',
 '/pt/partidas/865e8350/Vasco-da-Gama-Gremio-2024Abril14-Serie-A',
 '/pt/partidas/d3926429/Corinthians-Atletico-Mineiro-2024Abril14-Serie-A',
 '/pt/partidas/d95fadf2/Atletico-Goianiense-Flamengo-2024Abril14-Serie-A',
 '/pt/partidas/37353de0/Cruzeiro-Botafogo-RJ-2024Abril14-Serie-A',
 '/pt/partidas/e8d2edb8/Vitoria-Palmeiras-2024Abril14-Serie-A',
 '/pt/partidas/5aee04aa/Fluminense-Red-Bull-Bragantino-2024Abril13-Serie-A',
 '/pt/partidas/93f72e31/Sao-Paulo-Fortaleza-2024Abril13-Serie-A',
 '/pt/partidas/12462f89/Gremio-Athletico-Paranaense-2024Abril17-Serie-A',
 '/pt/partidas/4ad46089/Red-Bull-Bragantino-Vasco-da-Gama-2024Abril17-Serie-A',
 '/pt/partidas/11eccb6a/Juventude-Corinthians-2024Abril17-Serie-A',
 '/pt/partidas/1d4e7bb0/Atletico-Mineiro-Criciuma-2024Abril17-Serie-A',
 '/pt/partidas/5447208f/Palmeiras-Internacional-2024Abril17-Serie-A',
 '/pt/partidas/69ea969f/Fortaleza-Cruzeiro-2024Abril17-Serie-A',
 '/pt/partidas/c7829e3b/Bahia-Fluminense-2024Abril16-Serie-A',
 '/pt/partidas/8929c613/Flamengo-Sao-Paulo-2024Abril17-Serie-A',
 '/pt/partidas/4752f8cc/Botafogo-RJ-Atletico-Goianiense-2024Abril18-Serie-A',
 '/pt/partidas/85ba5adf/Fluminense-Vasco-da-Gama-2024Abril20-Serie-A',
 '/pt/partidas/45a73a6c/Red-Bull-Bragantino-Corinthians-2024Abril20-Serie-A',
 '/pt/partidas/891473c5/Gremio-Cuiaba-2024Abril20-Serie-A',
 '/pt/partidas/0d52ac06/Vitoria-Bahia-2024Abril21-Serie-A',
 '/pt/partidas/a47977b4/Palmeiras-Flamengo-2024Abril21-Serie-A',
 '/pt/partidas/eccd538c/Athletico-Paranaense-Internacional-2024Abril21-Serie-A',
 '/pt/partidas/90efe95f/Atletico-Goianiense-Sao-Paulo-2024Abril21-Serie-A',
 '/pt/partidas/ef588d50/Botafogo-RJ-Juventude-2024Abril21-Serie-A',
 '/pt/partidas/2805e796/Atletico-Mineiro-Cruzeiro-2024Abril20-Serie-A',
 '/pt/partidas/ba508006/Vasco-da-Gama-Criciuma-2024Abril27-Serie-A',
 '/pt/partidas/069d6245/Cuiaba-Atletico-Mineiro-2024Abril27-Serie-A',
 '/pt/partidas/c6c5b0eb/Flamengo-Botafogo-RJ-2024Abril28-Serie-A',
 '/pt/partidas/2ec6867f/Cruzeiro-Vitoria-2024Abril28-Serie-A',
 '/pt/partidas/a8cf2dc2/Corinthians-Fluminense-2024Abril28-Serie-A',
 '/pt/partidas/4bfd8bae/Fortaleza-Red-Bull-Bragantino-2024Abril28-Serie-A',
 '/pt/partidas/8a55364b/Juventude-Athletico-Paranaense-2024Abril28-Serie-A',
 '/pt/partidas/de23a072/Internacional-Atletico-Goianiense-2024Abril28-Serie-A',
 '/pt/partidas/8c6f889c/Bahia-Gremio-2024Abril27-Serie-A',
 '/pt/partidas/8610ca29/Sao-Paulo-Palmeiras-2024Abril29-Serie-A',
 '/pt/partidas/deddd3ba/Fluminense-Atletico-Mineiro-2024Maio4-Serie-A',
 '/pt/partidas/4040e59f/Red-Bull-Bragantino-Flamengo-2024Maio4-Serie-A',
 '/pt/partidas/220684d8/Vitoria-Sao-Paulo-2024Maio5-Serie-A',
 '/pt/partidas/87ea58c7/Athletico-Paranaense-Vasco-da-Gama-2024Maio5-Serie-A',
 '/pt/partidas/d141f173/Cuiaba-Palmeiras-2024Maio5-Serie-A',
 '/pt/partidas/4537cc2f/Botafogo-RJ-Bahia-2024Maio5-Serie-A',
 '/pt/partidas/2e483295/Corinthians-Fortaleza-2024Maio4-Serie-A',
 '/pt/partidas/206a47aa/Flamengo-Corinthians-2024Maio11-Serie-A',
 '/pt/partidas/73bffc53/Palmeiras-Athletico-Paranaense-2024Maio12-Serie-A',
 '/pt/partidas/c7b55047/Atletico-Goianiense-Cruzeiro-2024Maio12-Serie-A',
 '/pt/partidas/fec27399/Fortaleza-Botafogo-RJ-2024Maio12-Serie-A',
 '/pt/partidas/b6e02908/Bahia-Red-Bull-Bragantino-2024Maio12-Serie-A',
 '/pt/partidas/cbb799c7/Vasco-da-Gama-Vitoria-2024Maio12-Serie-A',
 '/pt/partidas/7a7905d4/Sao-Paulo-Fluminense-2024Maio13-Serie-A',
 '/pt/partidas/1ad27438/Vitoria-Atletico-Goianiense-2024Junho1-Serie-A',
 '/pt/partidas/a0f3804e/Gremio-Red-Bull-Bragantino-2024Junho1-Serie-A',
 '/pt/partidas/9fe8507f/Cuiaba-Internacional-2024Junho1-Serie-A',
 '/pt/partidas/004af2f4/Fluminense-Juventude-2024Junho1-Serie-A',
 '/pt/partidas/3791ec20/Criciuma-Palmeiras-2024Junho2-Serie-A',
 '/pt/partidas/7d73c766/Atletico-Mineiro-Bahia-2024Junho2-Serie-A',
 '/pt/partidas/af654f03/Classico-dos-Milhoes-Vasco-da-Gama-Flamengo-2024Junho2-Serie-A',
 '/pt/partidas/0a5442e8/Sao-Paulo-Cruzeiro-2024Junho2-Serie-A',
 '/pt/partidas/3132e57e/Fortaleza-Athletico-Paranaense-2024Junho2-Serie-A',
 '/pt/partidas/dd86edfe/Corinthians-Botafogo-RJ-2024Junho1-Serie-A',
 '/pt/partidas/f22a2249/Cuiaba-Vitoria-2024Junho5-Serie-A',
 '/pt/partidas/51c220ef/Juventude-Atletico-Goianiense-2024Junho5-Serie-A',
 '/pt/partidas/dd01c27d/Criciuma-Cuiaba-2024Junho9-Serie-A',
 '/pt/partidas/4a537b33/Juventude-Vitoria-2024Junho11-Serie-A',
 '/pt/partidas/9ece2587/Atletico-Goianiense-Corinthians-2024Junho11-Serie-A',
 '/pt/partidas/c607537a/Botafogo-RJ-Fluminense-2024Junho11-Serie-A',
 '/pt/partidas/a451de49/Red-Bull-Bragantino-Atletico-Mineiro-2024Junho11-Serie-A',
 '/pt/partidas/35b9c8c7/Cruzeiro-Cuiaba-2024Junho13-Serie-A',
 '/pt/partidas/98b435e7/Flamengo-Gremio-2024Junho13-Serie-A',
 '/pt/partidas/a847c862/Internacional-Sao-Paulo-2024Junho13-Serie-A',
 '/pt/partidas/e3954d94/Athletico-Paranaense-Criciuma-2024Junho13-Serie-A',
 '/pt/partidas/930871d8/Bahia-Fortaleza-2024Junho13-Serie-A',
 '/pt/partidas/f17f40e0/Palmeiras-Vasco-da-Gama-2024Junho13-Serie-A',
 '/pt/partidas/307328b7/Red-Bull-Bragantino-Juventude-2024Junho15-Serie-A',
 '/pt/partidas/25aab3a0/Vitoria-Internacional-2024Junho16-Serie-A',
 '/pt/partidas/46286d05/Classico-Majestoso-Corinthians-Sao-Paulo-2024Junho16-Serie-A',
 '/pt/partidas/64a04e10/Athletico-Paranaense-Flamengo-2024Junho16-Serie-A',
 '/pt/partidas/4ebfaebd/Cuiaba-Fortaleza-2024Junho16-Serie-A',
 '/pt/partidas/391366f7/Criciuma-Bahia-2024Junho16-Serie-A',
 '/pt/partidas/4257cbc2/Gremio-Botafogo-RJ-2024Junho16-Serie-A',
 '/pt/partidas/a9931e51/Vasco-da-Gama-Cruzeiro-2024Junho16-Serie-A',
 '/pt/partidas/29cda5d2/Fluminense-Atletico-Goianiense-2024Junho15-Serie-A',
 '/pt/partidas/1c9d1b2d/Atletico-Mineiro-Palmeiras-2024Junho17-Serie-A',
 '/pt/partidas/1a19415b/Atletico-Goianiense-Criciuma-2024Junho19-Serie-A',
 '/pt/partidas/9c325553/Botafogo-RJ-Athletico-Paranaense-2024Junho19-Serie-A',
 '/pt/partidas/081091ac/Fortaleza-Gremio-2024Junho19-Serie-A',
 '/pt/partidas/a63c79b5/Sao-Paulo-Cuiaba-2024Junho19-Serie-A',
 '/pt/partidas/d0569570/Juventude-Vasco-da-Gama-2024Junho19-Serie-A',
 '/pt/partidas/30eb9fe9/Vitoria-Atletico-Mineiro-2024Junho20-Serie-A',
 '/pt/partidas/ae4b29ce/Flamengo-Bahia-2024Junho20-Serie-A',
 '/pt/partidas/06841ffb/Internacional-Corinthians-2024Junho19-Serie-A',
 '/pt/partidas/324bf54d/Cruzeiro-Fluminense-2024Junho19-Serie-A',
 '/pt/partidas/7b1bef73/Palmeiras-Red-Bull-Bragantino-2024Junho20-Serie-A',
 '/pt/partidas/ef21323a/Criciuma-Botafogo-RJ-2024Junho22-Serie-A',
 '/pt/partidas/134bd2e7/Cuiaba-Atletico-Goianiense-2024Junho22-Serie-A',
 '/pt/partidas/16c8a020/Gremio-Internacional-2024Junho22-Serie-A',
 '/pt/partidas/2710ddc4/Fluminense-Flamengo-2024Junho23-Serie-A',
 '/pt/partidas/4afab374/Bahia-Cruzeiro-2024Junho23-Serie-A',
 '/pt/partidas/9f68e36c/Athletico-Paranaense-Corinthians-2024Junho23-Serie-A',
 '/pt/partidas/31001bc3/Atletico-Mineiro-Fortaleza-2024Junho23-Serie-A',
 '/pt/partidas/6c5678df/Palmeiras-Juventude-2024Junho23-Serie-A',
 '/pt/partidas/93b80bf5/Red-Bull-Bragantino-Vitoria-2024Junho23-Serie-A',
 '/pt/partidas/57771a62/Vasco-da-Gama-Sao-Paulo-2024Junho22-Serie-A',
 '/pt/partidas/00bd5d37/Botafogo-RJ-Red-Bull-Bragantino-2024Junho26-Serie-A',
 '/pt/partidas/83e0aea0/Cruzeiro-Athletico-Paranaense-2024Junho26-Serie-A',
 '/pt/partidas/0fd769cc/Juventude-Flamengo-2024Junho26-Serie-A',
 '/pt/partidas/4ad7fbcc/Atletico-Goianiense-Gremio-2024Junho26-Serie-A',
 '/pt/partidas/7ff3c7d6/Corinthians-Cuiaba-2024Junho26-Serie-A',
 '/pt/partidas/a15030a1/Fluminense-Vitoria-2024Junho27-Serie-A',
 '/pt/partidas/0f056001/Sao-Paulo-Criciuma-2024Junho27-Serie-A',
 '/pt/partidas/0d6673b1/Bahia-Vasco-da-Gama-2024Junho26-Serie-A',
 '/pt/partidas/2895ef08/Internacional-Atletico-Mineiro-2024Junho26-Serie-A',
 '/pt/partidas/ec9e81b1/Fortaleza-Palmeiras-2024Junho26-Serie-A',
 '/pt/partidas/44acb90c/Cuiaba-Red-Bull-Bragantino-2024Junho29-Serie-A',
 '/pt/partidas/f8fdc399/Vasco-da-Gama-Botafogo-RJ-2024Junho29-Serie-A',
 '/pt/partidas/56af3243/Atletico-Mineiro-Atletico-Goianiense-2024Junho30-Serie-A',
 '/pt/partidas/4556317d/Sao-Paulo-Bahia-2024Junho30-Serie-A',
 '/pt/partidas/7f6df1bb/Fortaleza-Juventude-2024Junho30-Serie-A',
 '/pt/partidas/a8d11509/Gremio-Fluminense-2024Junho30-Serie-A',
 '/pt/partidas/8b8dd0f5/Flamengo-Cruzeiro-2024Junho30-Serie-A',
 '/pt/partidas/9f18fad7/Criciuma-Internacional-2024Junho30-Serie-A',
 '/pt/partidas/c0218242/Vitoria-Athletico-Paranaense-2024Junho30-Serie-A',
 '/pt/partidas/e89f509a/Palmeiras-Corinthians-2024Julho1-Serie-A',
 '/pt/partidas/eda9a9d8/Cuiaba-Botafogo-RJ-2024Julho3-Serie-A',
 '/pt/partidas/2d965d43/Vasco-da-Gama-Fortaleza-2024Julho3-Serie-A',
 '/pt/partidas/bcdf6fef/Criciuma-Cruzeiro-2024Julho3-Serie-A',
 '/pt/partidas/4c989da3/Gremio-Palmeiras-2024Julho4-Serie-A',
 '/pt/partidas/c529021c/Bahia-Juventude-2024Julho4-Serie-A',
 '/pt/partidas/c7f01a78/Corinthians-Vitoria-2024Julho4-Serie-A',
 '/pt/partidas/db28e378/Fluminense-Internacional-2024Julho4-Serie-A',
 '/pt/partidas/5d6f4b6b/Athletico-Paranaense-Sao-Paulo-2024Julho3-Serie-A',
 '/pt/partidas/981e26b6/Red-Bull-Bragantino-Atletico-Goianiense-2024Julho3-Serie-A',
 '/pt/partidas/dd8e8da8/Atletico-Mineiro-Flamengo-2024Julho3-Serie-A',
 '/pt/partidas/26310ed9/Flamengo-Cuiaba-2024Julho6-Serie-A',
 '/pt/partidas/86a1d64d/Sao-Paulo-Red-Bull-Bragantino-2024Julho6-Serie-A',
 '/pt/partidas/3672f0cf/Fortaleza-Fluminense-2024Julho7-Serie-A',
 '/pt/partidas/a150942f/Juventude-Gremio-2024Julho7-Serie-A',
 '/pt/partidas/ddff9788/Cruzeiro-Corinthians-2024Julho7-Serie-A',
 '/pt/partidas/463057f1/Internacional-Vasco-da-Gama-2024Julho7-Serie-A',
 '/pt/partidas/c4d413bf/Atletico-Goianiense-Athletico-Paranaense-2024Julho7-Serie-A',
 '/pt/partidas/cf1bcd5e/Palmeiras-Bahia-2024Julho7-Serie-A',
 '/pt/partidas/e777d3dc/Vitoria-Criciuma-2024Julho7-Serie-A',
 '/pt/partidas/76d329cb/Botafogo-RJ-Atletico-Mineiro-2024Julho7-Serie-A',
 '/pt/partidas/5b7823ea/Gremio-Cruzeiro-2024Julho10-Serie-A',
 '/pt/partidas/2330ae6e/Athletico-Paranaense-Bahia-2024Julho10-Serie-A',
 '/pt/partidas/f260927e/Vasco-da-Gama-Corinthians-2024Julho10-Serie-A',
 '/pt/partidas/0523260c/Palmeiras-Atletico-Goianiense-2024Julho11-Serie-A',
 '/pt/partidas/1d899c19/Flamengo-Fortaleza-2024Julho11-Serie-A',
 '/pt/partidas/d6018c14/Criciuma-Fluminense-2024Julho11-Serie-A',
 '/pt/partidas/945b07dc/Vitoria-Botafogo-RJ-2024Julho11-Serie-A',
 '/pt/partidas/e68fc471/Atletico-Mineiro-Sao-Paulo-2024Julho11-Serie-A',
 '/pt/partidas/16b782fd/Cruzeiro-Red-Bull-Bragantino-2024Julho13-Serie-A',
 '/pt/partidas/96dab114/Bahia-Cuiaba-2024Julho13-Serie-A',
 '/pt/partidas/8cd99c81/Juventude-Atletico-Mineiro-2024Julho16-Serie-A',
 '/pt/partidas/c20dad05/Atletico-Goianiense-Vasco-da-Gama-2024Julho17-Serie-A',
 '/pt/partidas/1662bfc9/Sao-Paulo-Gremio-2024Julho17-Serie-A',
 '/pt/partidas/4e96eb28/Corinthians-Criciuma-2024Julho16-Serie-A',
 '/pt/partidas/d828c590/Fortaleza-Vitoria-2024Julho17-Serie-A',
 '/pt/partidas/f2802382/Botafogo-RJ-Palmeiras-2024Julho17-Serie-A',
 '/pt/partidas/7aa9d167/Flamengo-Criciuma-2024Julho20-Serie-A',
 '/pt/partidas/18ff17dd/Botafogo-RJ-Internacional-2024Julho20-Serie-A',
 '/pt/partidas/58dfa833/Gremio-Vitoria-2024Julho21-Serie-A',
 '/pt/partidas/1534c147/Bahia-Corinthians-2024Julho21-Serie-A',
 '/pt/partidas/57c57174/Atletico-Mineiro-Vasco-da-Gama-2024Julho21-Serie-A',
 '/pt/partidas/658eff3c/Red-Bull-Bragantino-Athletico-Paranaense-2024Julho21-Serie-A',
 '/pt/partidas/7ed52b26/Fortaleza-Atletico-Goianiense-2024Julho21-Serie-A',
 '/pt/partidas/e4fcb89c/Juventude-Sao-Paulo-2024Julho21-Serie-A',
 '/pt/partidas/cedc908c/Cuiaba-Fluminense-2024Julho21-Serie-A',
 '/pt/partidas/ae87e6ed/Palmeiras-Cruzeiro-2024Julho20-Serie-A',
 '/pt/partidas/39ce100c/Criciuma-Fortaleza-2024Julho24-Serie-A',
 '/pt/partidas/4293655d/Cruzeiro-Juventude-2024Julho24-Serie-A',
 '/pt/partidas/4c0485f1/Sao-Paulo-Botafogo-RJ-2024Julho24-Serie-A',
 '/pt/partidas/271e5c00/Vitoria-Flamengo-2024Julho24-Serie-A',
 '/pt/partidas/00062d3c/Corinthians-Gremio-2024Julho25-Serie-A',
 '/pt/partidas/4718c1cd/Atletico-Goianiense-Bahia-2024Julho24-Serie-A',
 '/pt/partidas/fcb3a1d2/Fluminense-Palmeiras-2024Julho24-Serie-A',
 '/pt/partidas/884db190/Palmeiras-Vitoria-2024Julho27-Serie-A',
 '/pt/partidas/b4a136d6/Juventude-Criciuma-2024Julho27-Serie-A',
 '/pt/partidas/06a41b67/Bahia-Internacional-2024Julho27-Serie-A',
 '/pt/partidas/cb781e8a/Red-Bull-Bragantino-Fluminense-2024Julho28-Serie-A',
 '/pt/partidas/fe7b7eb3/Flamengo-Atletico-Goianiense-2024Julho28-Serie-A',
 '/pt/partidas/c0e77847/Cuiaba-Athletico-Paranaense-2024Julho28-Serie-A',
 '/pt/partidas/6b6915a6/Atletico-Mineiro-Corinthians-2024Julho28-Serie-A',
 '/pt/partidas/79177145/Gremio-Vasco-da-Gama-2024Julho28-Serie-A',
 '/pt/partidas/e929d90c/Botafogo-RJ-Cruzeiro-2024Julho27-Serie-A',
 '/pt/partidas/f514c298/Fortaleza-Sao-Paulo-2024Julho27-Serie-A',
 '/pt/partidas/8746caf6/Vitoria-Cuiaba-2024Agosto3-Serie-A',
 '/pt/partidas/4348e241/Vasco-da-Gama-Red-Bull-Bragantino-2024Agosto3-Serie-A',
 '/pt/partidas/c1cfad94/Atletico-Goianiense-Botafogo-RJ-2024Agosto3-Serie-A',
 '/pt/partidas/e4bd97f5/Criciuma-Atletico-Mineiro-2024Agosto3-Serie-A',
 '/pt/partidas/84ad3b2c/Fluminense-Bahia-2024Agosto4-Serie-A',
 '/pt/partidas/8d8133f9/Corinthians-Juventude-2024Agosto4-Serie-A',
 '/pt/partidas/e4136a2b/Athletico-Paranaense-Gremio-2024Agosto4-Serie-A',
 '/pt/partidas/0ea5728b/Internacional-Palmeiras-2024Agosto4-Serie-A',
 '/pt/partidas/03c34ee9/Sao-Paulo-Flamengo-2024Agosto3-Serie-A',
 '/pt/partidas/ae2c8909/Cruzeiro-Fortaleza-2024Agosto5-Serie-A',
 '/pt/partidas/847a24c6/Fortaleza-Criciuma-2024Agosto10-Serie-A',
 '/pt/partidas/09ccc6cb/Cuiaba-Gremio-2024Agosto10-Serie-A',
 '/pt/partidas/167fb7f9/Juventude-Botafogo-RJ-2024Agosto11-Serie-A',
 '/pt/partidas/2e98871f/Sao-Paulo-Atletico-Goianiense-2024Agosto11-Serie-A',
 '/pt/partidas/f7b319c1/Flamengo-Palmeiras-2024Agosto11-Serie-A',
 '/pt/partidas/f9bd370e/Bahia-Vitoria-2024Agosto11-Serie-A',
 '/pt/partidas/054386b8/Internacional-Athletico-Paranaense-2024Agosto11-Serie-A',
 '/pt/partidas/0da8aa4b/Cruzeiro-Atletico-Mineiro-2024Agosto10-Serie-A',
 '/pt/partidas/543a286f/Corinthians-Red-Bull-Bragantino-2024Agosto10-Serie-A',
 '/pt/partidas/e8c91184/Vasco-da-Gama-Fluminense-2024Agosto10-Serie-A',
 '/pt/partidas/9f6a7147/Internacional-Juventude-2024Agosto14-Serie-A',
 '/pt/partidas/8a93999b/Atletico-Mineiro-Cuiaba-2024Agosto17-Serie-A',
 '/pt/partidas/d56320ae/Gremio-Bahia-2024Agosto17-Serie-A',
 '/pt/partidas/3f87541a/Red-Bull-Bragantino-Fortaleza-2024Agosto17-Serie-A',
 '/pt/partidas/12ad16ea/Criciuma-Vasco-da-Gama-2024Agosto18-Serie-A',
 '/pt/partidas/79a0b727/Palmeiras-Sao-Paulo-2024Agosto18-Serie-A',
 '/pt/partidas/917e890f/Atletico-Goianiense-Internacional-2024Agosto18-Serie-A',
 '/pt/partidas/988ff3e3/Athletico-Paranaense-Juventude-2024Agosto18-Serie-A',
 '/pt/partidas/ba80f8ac/Botafogo-RJ-Flamengo-2024Agosto18-Serie-A',
 '/pt/partidas/abab024d/Fluminense-Corinthians-2024Agosto17-Serie-A',
 '/pt/partidas/884e2774/Vitoria-Cruzeiro-2024Agosto19-Serie-A',
 '/pt/partidas/6fb2b1d3/Atletico-Goianiense-Juventude-2024Agosto24-Serie-A',
 '/pt/partidas/693cf3cb/Palmeiras-Cuiaba-2024Agosto24-Serie-A',
 '/pt/partidas/16714502/Criciuma-Gremio-2024Agosto25-Serie-A',
 '/pt/partidas/7f4e3af4/Bahia-Botafogo-RJ-2024Agosto25-Serie-A',
 '/pt/partidas/c0a8d1ea/Fortaleza-Corinthians-2024Agosto25-Serie-A',
 '/pt/partidas/79532d5b/Sao-Paulo-Vitoria-2024Agosto25-Serie-A',
 '/pt/partidas/0064222d/Internacional-Cruzeiro-2024Agosto25-Serie-A',
 '/pt/partidas/268c1068/Flamengo-Red-Bull-Bragantino-2024Agosto25-Serie-A',
 '/pt/partidas/0b5f6fda/Atletico-Mineiro-Fluminense-2024Agosto24-Serie-A',
 '/pt/partidas/c37ad833/Vasco-da-Gama-Athletico-Paranaense-2024Agosto26-Serie-A',
 '/pt/partidas/96cdceb8/Cruzeiro-Internacional-2024Agosto28-Serie-A',
 '/pt/partidas/5fe90dc4/Criciuma-Red-Bull-Bragantino-2024Agosto28-Serie-A',
 '/pt/partidas/12d1e09f/Cuiaba-Criciuma-2024Agosto31-Serie-A',
 '/pt/partidas/0e8cf33e/Cruzeiro-Atletico-Goianiense-2024Setembro1-Serie-A',
 '/pt/partidas/87ef338c/Gremio-Atletico-Mineiro-2024Setembro1-Serie-A',
 '/pt/partidas/c2e50275/Corinthians-Flamengo-2024Setembro1-Serie-A',
 '/pt/partidas/1d332259/Juventude-Internacional-2024Setembro1-Serie-A',
 '/pt/partidas/9818b8f0/Athletico-Paranaense-Palmeiras-2024Setembro1-Serie-A',
 '/pt/partidas/ba9764f8/Fluminense-Sao-Paulo-2024Setembro1-Serie-A',
 '/pt/partidas/c9178fde/Vitoria-Vasco-da-Gama-2024Setembro1-Serie-A',
 '/pt/partidas/fa27d6de/Red-Bull-Bragantino-Bahia-2024Setembro1-Serie-A',
 '/pt/partidas/fe3afc8c/Botafogo-RJ-Fortaleza-2024Agosto31-Serie-A',
 '/pt/partidas/81ad2795/Cuiaba-Juventude-2024Setembro5-Serie-A',
 '/pt/partidas/73b22908/Internacional-Fortaleza-2024Setembro11-Serie-A',
 '/pt/partidas/669c6eec/Atletico-Goianiense-Vitoria-2024Setembro14-Serie-A',
 '/pt/partidas/9ff2ccfb/Athletico-Paranaense-Fortaleza-2024Setembro14-Serie-A',
 '/pt/partidas/25d75bfc/Red-Bull-Bragantino-Gremio-2024Setembro15-Serie-A',
 '/pt/partidas/d78f88f7/Juventude-Fluminense-2024Setembro15-Serie-A',
 '/pt/partidas/f840653c/Palmeiras-Criciuma-2024Setembro15-Serie-A',
 '/pt/partidas/19ccb168/Classico-dos-Milhoes-Flamengo-Vasco-da-Gama-2024Setembro15-Serie-A',
 '/pt/partidas/24766b1d/Cruzeiro-Sao-Paulo-2024Setembro15-Serie-A',
 '/pt/partidas/95664a87/Bahia-Atletico-Mineiro-2024Setembro15-Serie-A',
 '/pt/partidas/96c9cb35/Botafogo-RJ-Corinthians-2024Setembro14-Serie-A',
 '/pt/partidas/d386688b/Internacional-Cuiaba-2024Setembro16-Serie-A',
 '/pt/partidas/9b226572/Vitoria-Juventude-2024Setembro21-Serie-A',
 '/pt/partidas/aa0683d1/Corinthians-Atletico-Goianiense-2024Setembro21-Serie-A',
 '/pt/partidas/64deb2a0/Fluminense-Botafogo-RJ-2024Setembro21-Serie-A',
 '/pt/partidas/cccfa1db/Vasco-da-Gama-Palmeiras-2024Setembro22-Serie-A',
 '/pt/partidas/cd6767af/Atletico-Mineiro-Red-Bull-Bragantino-2024Setembro22-Serie-A',
 '/pt/partidas/1c4268a0/Cuiaba-Cruzeiro-2024Setembro22-Serie-A',
 '/pt/partidas/0a86cb63/Gremio-Flamengo-2024Setembro22-Serie-A',
 '/pt/partidas/16602935/Sao-Paulo-Internacional-2024Setembro22-Serie-A',
 '/pt/partidas/babc88a6/Criciuma-Athletico-Paranaense-2024Setembro22-Serie-A',
 '/pt/partidas/0b1ee8dc/Fortaleza-Bahia-2024Setembro21-Serie-A',
 '/pt/partidas/fbb40f13/Gremio-Criciuma-2024Setembro25-Serie-A',
 '/pt/partidas/0e53bd28/Red-Bull-Bragantino-Internacional-2024Setembro25-Serie-A',
 '/pt/partidas/b13912c8/Palmeiras-Atletico-Mineiro-2024Setembro28-Serie-A',
 '/pt/partidas/71fc3558/Juventude-Red-Bull-Bragantino-2024Setembro29-Serie-A',
 '/pt/partidas/4032bded/Fortaleza-Cuiaba-2024Setembro29-Serie-A',
 '/pt/partidas/72e965ed/Atletico-Goianiense-Fluminense-2024Setembro29-Serie-A',
 '/pt/partidas/ac52cacc/Classico-Majestoso-Sao-Paulo-Corinthians-2024Setembro29-Serie-A',
 '/pt/partidas/26feb496/Cruzeiro-Vasco-da-Gama-2024Setembro29-Serie-A',
 '/pt/partidas/7b02ac23/Internacional-Vitoria-2024Setembro29-Serie-A',
 '/pt/partidas/b2e0b425/Bahia-Criciuma-2024Setembro29-Serie-A',
 '/pt/partidas/b3539655/Flamengo-Athletico-Paranaense-2024Setembro29-Serie-A',
 '/pt/partidas/6549c685/Botafogo-RJ-Gremio-2024Setembro28-Serie-A',
 '/pt/partidas/2a9fef5e/Criciuma-Atletico-Goianiense-2024Outubro3-Serie-A',
 '/pt/partidas/e780b2c5/Fluminense-Cruzeiro-2024Outubro3-Serie-A',
 '/pt/partidas/5ec2a035/Red-Bull-Bragantino-Palmeiras-2024Outubro5-Serie-A',
 '/pt/partidas/a1af7d32/Athletico-Paranaense-Botafogo-RJ-2024Outubro5-Serie-A',
 '/pt/partidas/f759afc6/Atletico-Mineiro-Vitoria-2024Outubro5-Serie-A',
 '/pt/partidas/50134ef5/Cuiaba-Sao-Paulo-2024Outubro5-Serie-A',
 '/pt/partidas/2feabb9f/Corinthians-Internacional-2024Outubro5-Serie-A',
 '/pt/partidas/95ed39b1/Bahia-Flamengo-2024Outubro5-Serie-A',
 '/pt/partidas/986278fd/Gremio-Fortaleza-2024Outubro4-Serie-A',

In [11]:
tabela.to_csv(r'C:\Users\eduar\OneDrive\Desktop\DEV\Football\Brasileirao\links.csv', index= False)

In [12]:
import requests
from bs4 import BeautifulSoup
import pandas as pd

# URL da página
url = "https://fbref.com/pt/comps/24/cronograma/Serie-A-Resultados-e-Calendarios"
# Faz a requisição para a página
response = requests.get(url)
soup = BeautifulSoup(response.content, "html.parser")

# Função para extrair a tabela da página
def extrair_tabela(rows):
    headers = []
    data = []
    
    for row in rows:
        cols = row.find_all(['th', 'td'])
        if len(headers) == 0:  # A primeira linha será o cabeçalho
            headers = [col.get_text(strip=True) for col in cols]
        else:  # Demais linhas são dados
            data.append([col.get_text(strip=True) for col in cols])
    
    # Cria o DataFrame
    return pd.DataFrame(data, columns=headers)

# Encontra o container da tabela
table_container = soup.find('div', {'class': 'table_container'})
rows = table_container.find_all('tr')

# Extrai a tabela
tabela = extrair_tabela(rows)

# Encontra a coluna "Relatório da Partida" e coleta todos os links
links_relatorios = []
for row in rows:
    a_tag = row.find('a', text='Relatório da Partida')
    if a_tag:
        href = a_tag.get('href')
        if href and href != "#":  # Ignora links vazios ou "#" como marcador
            links_relatorios.append("https://fbref.com" + href)  # Adiciona a URL completa
        else:
            links_relatorios.append(None)
    else:
        links_relatorios.append(None)

# Adiciona a coluna de links na tabela, ajustando o tamanho da lista de links
tabela['Link Relatório'] = links_relatorios[:len(tabela)]

# Exibe o DataFrame resultante
print(tabela)

    Sem  Dia        Data Horário           Em casa   xG Resultado   xG  \
0     1  sáb  2024-04-13   18:30          Criciúma  0.7       1–1  0.6
1     1  sáb  2024-04-13   18:30     Internacional  1.9       2–1  0.7
2     1  dom  2024-04-14   16:00    Ath Paranaense  2.0       4–0  0.3
3     1  dom  2024-04-14   16:00     Vasco da Gama  0.9       2–1  1.2
4     1  dom  2024-04-14   16:00       Corinthians  0.5       0–0  0.3
..   ..  ...         ...     ...               ...  ...       ...  ...
432  38  dom  2024-12-08                    Grêmio
433  38  dom  2024-12-08                 Palmeiras
434  38  dom  2024-12-08                     Bahia
435  38  dom  2024-12-08                 Juventude
436  38  dom  2024-12-08          Atlético Mineiro

            Visitante Público                                  Local Árbitro  \
0           Juventude  12.804                Estádio Heriberto Hülse
1               Bahia  19.103            Estádio José Pinheiro Borba
2              Cuiabá  21.388                            Ligga Arena
3              Grêmio  17.722  Estádio Club de Regatas Vasco da Gama
4    Atlético Mineiro  44.285                      Neo Química Arena
..                ...     ...                                    ...     ...
432       Corinthians
433        Fluminense
434    Atl Goianiense
435          Cruzeiro
436    Ath Paranaense

     Relatório da Partida Notas  \
0    Relatório da Partida
1    Relatório da Partida
2    Relatório da Partida
3    Relatório da Partida
4    Relatório da Partida
..                    ...   ...
432             Confronto
433             Confronto
434             Confronto
435             Confronto
436             Confronto

                                        Link Relatório
0                                                 None
1    https://fbref.com/pt/partidas/60ef737d/Cricium...
2    https://fbref.com/pt/partidas/620b512a/Interna...
3    https://fbref.com/pt/partidas/086cf01e/Athleti...
4    https://fbref.com/pt/partidas/865e8350/Vasco-d...
..                                                 ...
432                                               None
433                                               None
434                                               None
435                                               None
436                                               None

[437 rows x 15 columns]

C:\Users\eduar\AppData\Local\Temp\ipykernel_7244\3111375208.py:36: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  a_tag = row.find('a', text='Relatório da Partida')

In [13]:
# Desloca a coluna "Link Relatório" uma linha para cima
tabela['Link Relatório'] = tabela['Link Relatório'].shift(-1)

In [14]:
tabela_final = tabela[~tabela['Link Relatório'].isna()]

In [15]:
tabela_final

,Sem,Dia,Data,Horário,Em casa,xG,Resultado,xG,Visitante,Público,Local,Árbitro,Relatório da Partida,Notas,Link Relatório
0,1,sáb,2024-04-13,18:30,Criciúma,0.7,1–1,0.6,Juventude,12.804,Estádio Heriberto Hülse,,Relatório da Partida,,https://fbref.com/pt/partidas/60ef737d/Cricium...
1,1,sáb,2024-04-13,18:30,Internacional,1.9,2–1,0.7,Bahia,19.103,Estádio José Pinheiro Borba,,Relatório da Partida,,https://fbref.com/pt/partidas/620b512a/Interna...
2,1,dom,2024-04-14,16:00,Ath Paranaense,2.0,4–0,0.3,Cuiabá,21.388,Ligga Arena,,Relatório da Partida,,https://fbref.com/pt/partidas/086cf01e/Athleti...
3,1,dom,2024-04-14,16:00,Vasco da Gama,0.9,2–1,1.2,Grêmio,17.722,Estádio Club de Regatas Vasco da Gama,,Relatório da Partida,,https://fbref.com/pt/partidas/865e8350/Vasco-d...
4,1,dom,2024-04-14,16:00,Corinthians,0.5,0–0,0.3,Atlético Mineiro,44.285,Neo Química Arena,,Relatório da Partida,,https://fbref.com/pt/partidas/d3926429/Corinth...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
393,34,sex,2024-11-22,21:30,Fluminense,0.8,2–2,1.3,Fortaleza,,Estadio Jornalista Mário Filho,Raphael Claus,Relatório da Partida,,https://fbref.com/pt/partidas/d8463264/Flumine...
395,35,dom,2024-11-24,16:00,Bahia,2.2,1–1,0.8,Ath Paranaense,,Itaipava Arena Fonte Nova,Rodrigo José Pereira de Lima,Relatório da Partida,,https://fbref.com/pt/partidas/571b8b37/Bahia-A...
396,35,dom,2024-11-24,16:00,Internacional,2.8,4–1,0.3,Red Bull Bragantino,,Estádio José Pinheiro Borba,Marcelo de Lima Henrique,Relatório da Partida,,https://fbref.com/pt/partidas/bd40427d/Interna...
397,35,dom,2024-11-24,16:00,Corinthians,1.2,3–1,0.3,Vasco da Gama,,Neo Química Arena,Davi de Oliveira Lacerda,Relatório da Partida,,https://fbref.com/pt/partidas/cc1dd787/Corinth...
398,35,sáb,2024-11-23,21:30,São Paulo,1.0,2–2,1.0,Atlético Mineiro,,Estádio do Morumbi,Alex Gomes Stefano,Relatório da Partida,,https://fbref.com/pt/partidas/45170f90/Sao-Pau...

In [16]:
tabela_final.to_csv(r'C:\Users\eduar\OneDrive\Desktop\DEV\Football\Brasileirao\links.csv', index= False)